# Generated by Django 3.0.8 on 2020-07-27 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200727_0326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
